"""token fields

Revision ID: 0487810210b4
Revises: 78bd963acf32
Create Date: 2025-10-18 13:42:18.252239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0487810210b4'
down_revision: Union[str, Sequence[str], None] = '78bd963acf32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'telegram_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='ID в Telegram')
    op.alter_column('students', 'telegram_username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='Username в Telegram')
    op.alter_column('students', 'age',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Возраст')
    op.alter_column('teachers', 'telegram_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='ID в Telegram')
    op.alter_column('teachers', 'telegram_username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='Username в Telegram')
    op.alter_column('teachers', 'age',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Возраст')
    op.add_column('tokens', sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'))
    op.add_column('tokens', sa.Column('used', sa.Boolean(), nullable=False, comment='Использован'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'used')
    op.drop_column('tokens', 'user_id')
    op.alter_column('teachers', 'age',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Возраст')
    op.alter_column('teachers', 'telegram_username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='Username в Telegram')
    op.alter_column('teachers', 'telegram_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='ID в Telegram')
    op.alter_column('students', 'age',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Возраст')
    op.alter_column('students', 'telegram_username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='Username в Telegram')
    op.alter_column('students', 'telegram_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='ID в Telegram')
    # ### end Alembic commands ###
