"""uuid student

Revision ID: 53750c264573
Revises: a2aa7b4139b3
Create Date: 2025-11-03 15:39:12.531816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53750c264573'
down_revision: Union[str, Sequence[str], None] = 'a2aa7b4139b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('hidden_applications_student_id_fkey'),
                       'hidden_applications', type_='foreignkey')
    op.drop_constraint(op.f('hidden_applications_application_id_fkey'),
                       'hidden_applications', type_='foreignkey')
    op.create_foreign_key(None, 'hidden_applications', 'students', [
                          'student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'hidden_applications', 'applications', [
                          'application_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('hidden_teachers_teacher_id_fkey'),
                       'hidden_teachers', type_='foreignkey')
    op.drop_constraint(op.f('hidden_teachers_student_id_fkey'),
                       'hidden_teachers', type_='foreignkey')
    op.create_foreign_key(None, 'hidden_teachers', 'teachers', [
                          'teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'hidden_teachers', 'students', [
                          'student_id'], ['id'], ondelete='CASCADE')
    op.alter_column('students', 'id',
                    existing_type=sa.INTEGER(),
                    comment='ID студента',
                    existing_nullable=False)
    op.drop_constraint(op.f('teacher_subjects_teacher_id_fkey'),
                       'teacher_subjects', type_='foreignkey')
    op.drop_constraint(op.f('teacher_subjects_subject_id_fkey'),
                       'teacher_subjects', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_subjects', 'subjects', [
                          'subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teacher_subjects', 'teachers', [
                          'teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
