"""teacher_id_hidden_apps

Revision ID: 749e26d37930
Revises: 20251103_add_subjects
Create Date: 2025-11-08 08:03:23.976005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749e26d37930'
down_revision: Union[str, Sequence[str], None] = '20251103_add_subjects'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'student_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='ID студента',
               existing_nullable=False)
    op.add_column('hidden_applications', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('hidden_applications_student_id_fkey'), 'hidden_applications', type_='foreignkey')
    op.create_foreign_key(None, 'hidden_applications', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.drop_column('hidden_applications', 'student_id')
    op.alter_column('hidden_teachers', 'student_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('matchs', 'student_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='ID студента',
               existing_nullable=False)
    op.alter_column('reviews', 'student_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='ID студента, оставившего отзыв',
               existing_nullable=False)
    op.alter_column('students', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='ID студента',
               existing_nullable=False,
               existing_server_default=sa.text("nextval('students_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
