"""refresh data

Revision ID: a2aa7b4139b3
Revises: 0487810210b4
Create Date: 2025-10-25 08:39:00.603048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2aa7b4139b3'
down_revision: Union[str, Sequence[str], None] = '0487810210b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('refresh_id', sa.String(
        length=255), nullable=True, comment='ID refresh токена'))
    op.add_column('students', sa.Column('ip', sa.String(
        length=255), nullable=True, comment='IP адрес'))
    op.create_unique_constraint(None, 'students', ['telegram_username'])
    op.create_unique_constraint(None, 'students', ['telegram_id'])
    op.add_column('teachers', sa.Column('refresh_id', sa.String(
        length=255), nullable=True, comment='ID refresh токена'))
    op.add_column('teachers', sa.Column('ip', sa.String(
        length=255), nullable=True, comment='IP адрес'))
    op.create_unique_constraint(None, 'teachers', ['telegram_username'])
    op.create_unique_constraint(None, 'teachers', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_column('teachers', 'ip')
    op.drop_column('teachers', 'refresh_id')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'ip')
    op.drop_column('students', 'refresh_id')
    # ### end Alembic commands ###
